// Static option lists for the filter panel and settings.
window.DATA = {
  DEFAULT_FILTERS: {
    includeTags: [],
    excludeTags: [],
    priceMode: 'any',
    priceMin: '',
    priceMax: '',
    onSale: false,
    minDiscount: 0,
    minPositive: 0,
    minReviews: '',
    maxReviews: '',
    yearFrom: '',
    yearTo: '',
    hideUnreleased: true,
    players: [],
    features: [],
    os: [],
    deck: 'any',
    vr: 'any',
    language: '',
    hideEarlyAccess: false,
    hideAdult: true,
    topSellers: false,
    excludeOwned: false,
    noRepeat: true,
    playtime: 'any',
    playtimeHours: 2,
  },

  PRESETS: [
    { id: 'gems', name: 'Скрытые жемчужины', hint: '90%+ и не больше 3000 отзывов', filters: { minPositive: 90, minReviews: 50, maxReviews: 3000 } },
    { id: 'classic', name: 'Проверенная классика', hint: '85%+, от 10 000 отзывов, до 2016 года', filters: { minPositive: 85, minReviews: 10000, yearTo: 2016 } },
    { id: 'free', name: 'Бесплатные хиты', hint: 'Бесплатно, 80%+, от 1000 отзывов', filters: { priceMode: 'free', minPositive: 80, minReviews: 1000 } },
    { id: 'coop', name: 'Вечер в коопе', hint: 'Онлайн-кооператив, 80%+', filters: { players: [38], minPositive: 80, minReviews: 300 } },
    { id: 'fresh', name: 'Свежак', hint: `Вышло в ${new Date().getFullYear()} году, 75%+`, filters: { yearFrom: new Date().getFullYear(), minPositive: 75, minReviews: 30 } },
    { id: 'sale', name: 'Выгодная скидка', hint: 'Скидка от 50%, 80%+', filters: { onSale: true, minDiscount: 50, minPositive: 80, minReviews: 200 } },
    { id: 'deck', name: 'Для Steam Deck', hint: 'Проверено для Deck, 80%+', filters: { deck: 'verified', minPositive: 80, minReviews: 200 } },
  ],

  PLAYERS: [
    { id: 2, name: 'Для одного игрока' },
    { id: 1, name: 'Для нескольких игроков' },
    { id: 9, name: 'Кооператив' },
    { id: 38, name: 'Онлайн-кооператив' },
    { id: 39, name: 'Кооператив на одном экране' },
    { id: 48, name: 'Кооператив по LAN' },
    { id: 49, name: 'PvP' },
    { id: 36, name: 'Онлайн PvP' },
    { id: 37, name: 'PvP на одном экране' },
    { id: 20, name: 'MMO' },
    { id: 27, name: 'Кроссплатформенный мультиплеер' },
  ],

  FEATURES: [
    { id: 22, name: 'Достижения Steam' },
    { id: 29, name: 'Коллекционные карточки' },
    { id: 28, name: 'Полная поддержка контроллеров' },
    { id: 30, name: 'Мастерская Steam' },
    { id: 23, name: 'Steam Cloud' },
    { id: 44, name: 'Remote Play Together' },
    { id: 62, name: 'Семейный доступ' },
    { id: 17, name: 'Редактор уровней' },
  ],

  LANGUAGES: [
    { id: '', name: 'Любой' },
    { id: 'russian', name: 'Русский' },
    { id: 'english', name: 'Английский' },
    { id: 'ukrainian', name: 'Украинский' },
    { id: 'german', name: 'Немецкий' },
    { id: 'french', name: 'Французский' },
    { id: 'spanish', name: 'Испанский' },
    { id: 'italian', name: 'Итальянский' },
    { id: 'polish', name: 'Польский' },
    { id: 'brazilian', name: 'Португальский (Бразилия)' },
    { id: 'turkish', name: 'Турецкий' },
    { id: 'japanese', name: 'Японский' },
    { id: 'koreana', name: 'Корейский' },
    { id: 'schinese', name: 'Китайский (упр.)' },
  ],

  // currency is what Steam actually charges in the region; Belarus and Turkey are priced in USD by Steam.
  REGIONS: [
    { id: 'ru', name: 'Россия', currency: '₽' },
    { id: 'kz', name: 'Казахстан', currency: '₸' },
    { id: 'ua', name: 'Украина', currency: '₴' },
    { id: 'by', name: 'Беларусь', currency: '$', usdOnly: true },
    { id: 'us', name: 'США', currency: '$' },
    { id: 'de', name: 'Германия (ЕС)', currency: '€' },
    { id: 'pl', name: 'Польша', currency: 'zł' },
    { id: 'gb', name: 'Великобритания', currency: '£' },
    { id: 'tr', name: 'Турция', currency: '$', usdOnly: true },
    { id: 'br', name: 'Бразилия', currency: 'R$' },
    { id: 'jp', name: 'Япония', currency: '¥' },
  ],

  UI_LANGUAGES: [
    { id: 'russian', name: 'Русский' },
    { id: 'english', name: 'English' },
    { id: 'ukrainian', name: 'Українська' },
  ],

  DECK_LABELS: { 3: 'Проверено', 2: 'Играбельно', 1: 'Не поддерживается', 0: null },
};
